name: drupal-composer
recipe: drupal8
config:
  via: nginx
  php: '7.3'
  webroot: build/html
  database: mysql
  xdebug: true

env_file:
  -  .env

services:
  appserver:
    build:
      - composer install
    run:
      - /app/scripts/bash/install.sh

tooling:
  drush:
    service: appserver
    cmd: "/app/vendor/bin/drush --root=/app/build/html"
